[configcook]
extensions = [
    "configcook:extension_example",
    "configcook:pdb",
    # "zest.releaser",
]
parts = [
    "test",
    "cmd",
    "template",
]
# bin-directory = "../../bin"
copy_parts = "${:parts}"

[configcook_pdb]
# options for configcook:pdb extension
before = [
    # "pip",
]
after = [
    # "load_recipes",
    # "run_recipes",
]

[test]
recipe = "configcook:packages"
packages = [
    "zest.releaser",
    "colorama",
]

[cmd]
recipe = "configcook:commands"
# commands = ["ls -l"]
commands = """
    echo "This is a listing of the current directory:"

    ls
    """

[template]
recipe = "configcook:template"
input = """
    Configcook parts are: ${configcook:parts}
    Home directory in text is not expanded: ~
"""
output = "~/test-configcook.txt"
